In [1]:
import numpy as np        #넘파이 라이브러리 불러오기
import pandas as pd        #판다스 라이브러리 불러오기

In [2]:
import matplotlib as mpl  # 맷플로립 불러오기
import matplotlib.pyplot as plt  # 그래프 그리기 기능 불러오기
import matplotlib.font_manager as fm  # 폰트 매니저 실행


!apt-get update -qq         # apt-get 패키지 설치 명령어, -qq : 에러외 메세지 숨기기
!apt-get install fonts-nanum* -qq #나눔글꼴 설치

fe = fm.FontEntry(fname=r'/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic') #파일 저장되어있는 경로와 이름 설정
fm.fontManager.ttflist.insert(0, fe)  # Matplotlib에 폰트 추가
plt.rcParams.update({'font.size': 10, 'font.family': 'NanumGothic'}) #폰트설정

zsh:1: command not found: apt-get
zsh:1: no matches found: fonts-nanum*

In [4]:
import pandas as pd

# CSV 파일 경로 지정
file_path = '/Users/Star1/Desktop/부트캠프_파이썬 _실습/Python_Practice/데이터셋/원본 데이터/1. 목적지 데이터 원본 데이터/yangyang_stay_time_2022.csv'

# CSV 파일 불러오기
df = pd.read_csv(file_path, encoding='cp949')

# 데이터프레임 확인
df

      기준연월           지역명   체류시간
0   202201  전국 기초지자체별 평균  223.0
1   202201           양양군  281.0
2   202202  전국 기초지자체별 평균  212.0
3   202202           양양군  252.0
4   202203  전국 기초지자체별 평균  215.0
5   202203           양양군  256.0
6   202204  전국 기초지자체별 평균  199.0
7   202204           양양군  290.0
8   202205  전국 기초지자체별 평균  191.0
9   202205           양양군  270.0
10  202206  전국 기초지자체별 평균  206.0
11  202206           양양군  331.0
12  202207  전국 기초지자체별 평균  214.0
13  202207           양양군  392.0
14  202208  전국 기초지자체별 평균  210.0
15  202208           양양군  386.0
16  202209  전국 기초지자체별 평균  213.0
17  202209           양양군  336.0
18  202210  전국 기초지자체별 평균  191.0
19  202210           양양군  290.0
20  202211  전국 기초지자체별 평균  196.0
21  202211           양양군  290.0
22  202212  전국 기초지자체별 평균  204.0
23  202212           양양군  328.0

In [5]:
#기본정보 확인하기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기준연월    24 non-null     int64
 1   지역명     24 non-null     object
 2   체류시간    24 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 708.0+ bytes

In [6]:
#지역명 컬럼에서 영덕군만 필터링하기

column_name = '지역명'  # 기준으로 할 컬럼명 변수 생성
filtered_df = df[df[column_name] == '양양군']           # 기준컬럼이 특정조건('양양군')을 만족하는 새로운 데이터프레임 생성

filtered_df

      기준연월  지역명   체류시간
1   202201  양양군  281.0
3   202202  양양군  252.0
5   202203  양양군  256.0
7   202204  양양군  290.0
9   202205  양양군  270.0
11  202206  양양군  331.0
13  202207  양양군  392.0
15  202208  양양군  386.0
17  202209  양양군  336.0
19  202210  양양군  290.0
21  202211  양양군  290.0
23  202212  양양군  328.0

In [7]:
#쓸모없는 데이터(열) 삭제해주기 (지역명 컬럼)

filtered_df.drop('지역명', axis=1, inplace=True)        #axis가 1이면 열, 0이면 행을 기준으로 함수를 호출함

filtered_df

/var/folders/34/nfsz0w6s5rl3lqtq7z6j5p_h0000gp/T/ipykernel_22754/3995858803.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop('지역명', axis=1, inplace=True)        #axis가 1이면 열, 0이면 행을 기준으로 함수를 호출함

      기준연월   체류시간
1   202201  281.0
3   202202  252.0
5   202203  256.0
7   202204  290.0
9   202205  270.0
11  202206  331.0
13  202207  392.0
15  202208  386.0
17  202209  336.0
19  202210  290.0
21  202211  290.0
23  202212  328.0

In [7]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 1 to 23
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기준연월    12 non-null     int64
 1   체류시간    12 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 288.0 bytes

In [8]:
# 기준연월 컬럼을 인덱스로 바꿔주기

filtered_df.set_index(filtered_df.columns[0], inplace=True)
filtered_df

         체류시간
기준연월
202201  281.0
202202  252.0
202203  256.0
202204  290.0
202205  270.0
202206  331.0
202207  392.0
202208  386.0
202209  336.0
202210  290.0
202211  290.0
202212  328.0

In [10]:
#새로운 csv로 저장하기
filtered_df.to_csv('/Users/Star1/Desktop/부트캠프_파이썬 _실습/Python_Practice/데이터셋/원본 데이터/new_yangyang_tmap_2022.csv', index=True, encoding='cp949')
#index = True 는 인덱스도 저장하는 옵션, False는 인덱스는 저장하지 않도록 하는 옵션
#데이터 프레임에 한글이 있을경우, 인코딩으로 해줘야함. utf-8이나, cp949 중에서 utf8는 오류가 발생함